name = "Walnutpie"
uuid = "f4c315f0-1748-4b77-b1f4-814c5425fcbc"
authors = ["simonsteiger <simon.j.steiger@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
